name: McFAE
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - requests-futures==1.0.0
  - cudnn==7.6.5
  - python==3.7.6
  - h5py==2.10.0
  - python-levenshtein==0.12.0
  - pandas==1.0.1
  - ipykernel
  - pyteomics==4.2
  - scipy==1.5.0
  - hdf5==1.10.4
  - biopython==1.76
  - matplotlib==3.1.3
  - numpy==1.18.1
  - pytest==5.3.5
  - seaborn==0.10.0
  - scikit-learn==0.22.1
  - tensorboard==2.1.0
  - pip==20.0.2
  - joblib==0.14.1
  - tqdm==4.42.1
  - pillow==7.0.0
  - requests==2.22.0
  - keras==2.6.0
  - pip:
    - tensorflow-gpu==2.6.0
    - torch==1.10.0
    - pytoda@git+https://github.com/PaccMann/paccmann_datasets@0.2.4
    - paccmann_predictor@git+https://github.com/PaccMann/paccmann_predictor@0.0.4
    - rdkit-pypi==2021.9.1
    - shap==0.40.0
    - saliency==0.1.3
    - colour==0.1.5
    - "."
